import Head from 'next/head';
import Link from 'next/link';

export default function Register() {
  return (
    <div>
      <Head>
        <title> Register </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div
          className="h-screen bg-center bg-cover w-36"
          style={{ backgroundImage: "url('/images/pattern.jpeg')" }}
        ></div>
        <div className="flex flex-col justify-center pl-6">
          <div className="w-min-70">
            <h1 className="mb-2 text-lg font-medium">Sign Up</h1>
            <p className="mb-10 text-xs">
              By Continuing, you agree to our User Agreement and Privacy Policy
            </p>
            <form>
              <div className="mb-6">
                <input
                  type="checkbox"
                  className="mr-1 cursor-pointer"
                  id="agreement"
                />
                <label htmlFor="agreement" className="text-xs cursor-pointer">
                  I agree to get emails about cool stuff on Reddit
                </label>
              </div>
              <div className="mb-2">
                <input
                  type="email"
                  className="w-full px-3 py-2 bg-gray-100 border border-gray-400"
                  placeholder="Email"
                />
              </div>
              <div className="mb-2">
                <input
                  type="text"
                  className="w-full px-3 py-2 bg-gray-100 border border-gray-400"
                  placeholder="Username"
                />
              </div>
              <div className="mb-2">
                <input
                  type="password"
                  className="w-full px-3 py-2 bg-gray-100 border border-gray-400"
                  placeholder="Password"
                />
              </div>
              <button className="w-full py-2 mb-4 text-xs font-bold text-white uppercase bg-blue-500 border border-blue-500 rounded">
                Sign Up
              </button>
            </form>
            <small>
              Already a Redditor ?
              <Link href={'/login'}>
                <a href="" className="ml-1 text-blue-500 uppercase">
                  Log in
                </a>
              </Link>
            </small>
          </div>
        </div>
      </div>
    </div>
  );
}
