import axios, { Axios, AxiosError } from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import InputGroup from '../components/InputGroup';
import { useRouter } from 'next/router';
import { useAuthState } from '../context/Auth';
interface errorsState {
  email?: string;
  username?: string;
  password?: string;
}

const Register: React.FC = () => {
  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [agreement, setAgreement] = useState(false);
  const [errors, setErrors] = useState<errorsState>({});
  const { authenticated } = useAuthState();

  const router = useRouter();

  if (authenticated) {
    router.push('/');
  }

  const submitForm = async (e: FormEvent) => {
    e.preventDefault();
    try {
      await axios.post('auth/register', {
        email,
        password,
        username,
      });
      router.push('/login');
    } catch (error) {
      if (error instanceof AxiosError) {
        setErrors(error.response.data);
      }
      console.log(error);
    }
  };

  return (
    <div>
      <Head>
        <title> Register </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="flex bg-white">
        <div
          className="h-screen bg-center bg-cover w-36"
          style={{ backgroundImage: "url('/images/pattern.jpeg')" }}
        ></div>
        <div className="flex flex-col justify-center pl-6">
          <div className="min-w-90">
            <h1 className="mb-2 text-lg font-medium">Sign Up</h1>
            <p className="mb-10 text-xs">
              By Continuing, you agree to our User Agreement and Privacy Policy
            </p>
            <form onSubmit={submitForm}>
              <div className="mb-6">
                <input
                  type="checkbox"
                  className="mr-1 cursor-pointer"
                  checked={agreement}
                  onChange={(e) => setAgreement(e.target.checked)}
                  id="agreement"
                />
                <label htmlFor="agreement" className="text-xs cursor-pointer">
                  I agree to get emails about cool stuff on Reddit
                </label>
              </div>
              <InputGroup
                placeholder="Email"
                type="email"
                value={email}
                className="mb-2"
                setValue={setEmail}
                error={errors.email}
              />
              <InputGroup
                placeholder="Username"
                type="text"
                value={username}
                className="mb-2"
                setValue={setUsername}
                error={errors.username}
              />
              <InputGroup
                placeholder="Password"
                type="password"
                value={password}
                className="mb-4"
                setValue={setPassword}
                error={errors.password}
              />
              <button className="w-full py-2 mb-4 text-xs font-bold text-white uppercase bg-blue-500 border border-blue-500 rounded">
                Sign Up
              </button>
            </form>
            <small>
              Already a Redditor ?
              <Link href={'/login'}>
                <a className="ml-1 text-blue-500 uppercase">Log in</a>
              </Link>
            </small>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
