
on:
  push:
    branches: [master]

- name: Pull code, rebuild files and restart pm2 processes
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
    script: |
      cd /reddit.com
      git pull
      npm install 
