name: Pull code, rebuild files and restart pm2 processes
on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /reddit.com
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            node -v
            npm -v
            npm install
